{
 "title": "Data Platform Kafka - Development",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "topic", "label": "Topics", "query": { "query": "label_values(topic)" } },
   {
    "name": "consumer_group_id",
    "label": "consumer_group_id",
    "query": {
     "query": "label_values(consumer_group_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Global Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Partitions",
     "type": "stat",
     "description": "The total number of partitions across all the topics in the cluster",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "confluent_kafka_server_partition_count"
      }
     ]
    },
    {
     "title": "Total Active Connections",
     "type": "stat",
     "description": "The total number of active authenticated connections to the cluster",
     "gridPos": { "h": 6, "w": 6, "x": 7, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(confluent_kafka_server_active_connection_count)"
      }
     ]
    },
    {
     "title": "Total SASL_SSL Authentications (per min)",
     "type": "stat",
     "description": "The total number of successful SASL_SSL authentications per minute",
     "gridPos": { "h": 6, "w": 6, "x": 14, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(confluent_kafka_server_successful_authentication_count)"
      }
     ]
    }
   ]
  },
  {
   "title": "Topic Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Writes (per min)",
     "type": "stat",
     "description": "The total amount of writes  per minute to the cluster ",
     "gridPos": { "h": 4, "w": 5, "x": 1, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(confluent_kafka_server_received_bytes{topic=~\"$topic\"})"
      }
     ]
    },
    {
     "title": "Average Writes",
     "type": "stat",
     "description": "The average amount of writes to the cluster  (window for avg. depends on Grafana timeline)",
     "gridPos": { "h": 4, "w": 5, "x": 7, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(confluent_kafka_server_received_bytes{topic=~\"$topic\"})"
      }
     ]
    },
    {
     "title": "Current Reads (per min)",
     "type": "stat",
     "description": "The total amount of reads  per minute fom the cluster ",
     "gridPos": { "h": 4, "w": 5, "x": 13, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(confluent_kafka_server_sent_bytes{topic=~\"$topic\"})"
      }
     ]
    },
    {
     "title": "Average Reads",
     "type": "stat",
     "description": "The average amount of reads from the cluster  (window for avg. depends on Grafana timeline)",
     "gridPos": { "h": 4, "w": 5, "x": 19, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(confluent_kafka_server_sent_bytes{topic=~\"$topic\"})"
      }
     ]
    },
    {
     "title": "Current Writes (no. of records per min)",
     "type": "stat",
     "description": "The total number of records per minute written to the cluster ",
     "gridPos": { "h": 4, "w": 5, "x": 1, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(confluent_kafka_server_received_records{topic=~\"$topic\"})"
      }
     ]
    },
    {
     "title": "Average Writes (no. of records)",
     "type": "stat",
     "description": "The average number of records written to the cluster  (window for avg. depends on Grafana timeline)",
     "gridPos": { "h": 4, "w": 5, "x": 7, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(confluent_kafka_server_received_records{topic=~\"$topic\"})"
      }
     ]
    },
    {
     "title": "Current Reads (no. of records per min)",
     "type": "stat",
     "description": "The total number of records per minute read from the cluster ",
     "gridPos": { "h": 4, "w": 5, "x": 13, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(confluent_kafka_server_sent_records{topic=~\"$topic\"})"
      }
     ]
    },
    {
     "title": "Average Reads (no. of records)",
     "type": "stat",
     "description": "The average number of records read from the cluster  (window for avg. depends on Grafana timeline)",
     "gridPos": { "h": 4, "w": 5, "x": 19, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(confluent_kafka_server_sent_records{topic=~\"$topic\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Topic Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Writes (no. of records per min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (topic) (confluent_kafka_server_received_records{topic=~\"$topic\"})"
      }
     ]
    },
    {
     "title": "Current Reads (no. of records per min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (topic) (confluent_kafka_server_sent_records{topic=~\"$topic\"})"
      }
     ]
    }
   ]
  },
  { "title": "Consumer Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Consumer Group Lag",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum by (topic, consumer_group_id) (confluent_kafka_server_consumer_lag_offsets{topic=~\"$topic\", consumer_group_id=~\"$consumer_group_id\"})"
    }
   ]
  }
 ]
}