{
 "title": "MSK Consumers Overview",
 "description": "Prometheus monitoring for MSK cluster",
 "tags": [
  "msk",
  "kafka"
 ],
 "time": { "from": "2022-05-12T05:15:13.155Z", "to": "2022-05-12T06:51:39.108Z" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "EnvironmentCode",
    "label": "EnvironmentCode",
    "query": {
     "query": "label_values(kafka_consumer_group_ConsumerLagMetrics_Value{name=\"OffsetLag\"}, environmentcode)"
    }
   },
   {
    "name": "group",
    "query": {
     "query": "label_values(kafka_consumer_group_ConsumerLagMetrics_Value{name=\"OffsetLag\",environmentcode=~\"$EnvironmentCode.+\"}, groupId)"
    }
   },
   {
    "name": "topic",
    "query": {
     "query": "label_values(kafka_consumer_group_ConsumerLagMetrics_Value{name=\"OffsetLag\",environmentcode=~\"$EnvironmentCode.+\",groupId=~\"$group\"}, topic)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Consumer Lag per group/topic/partition",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max_over_time(kafka_consumer_group_ConsumerLagMetrics_Value{name=\"OffsetLag\", environmentcode=~\"$EnvironmentCode.+\", groupId=~\"$group\", topic=~\"$topic\"}[$__interval])",
     "legendFormat": "Topic={{topic}}:{{partition}} Grp: {{groupId}} "
    }
   ]
  },
  {
   "title": "Production/Consumption rate per topic/partition",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "Production Rate / 5m",
   "type": "timeseries",
   "description": "whether we're ingesting data to partition",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (topic, partition) (increase(kafka_log_Log_Value{name=\"LogEndOffset\",environmentcode=~\"$EnvironmentCode.+\", topic=~\"$topic\"}[5m])) ",
     "legendFormat": "{{topic}}:{{partition}}"
    }
   ]
  },
  {
   "title": "Consumption Rate / 5m",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (topic, partition) (increase(kafka_log_Log_Value{name=\"LogEndOffset\",environmentcode=~\"$EnvironmentCode.+\", topic=~\"$topic\"}[5m]))\n-\nsum by (topic, partition) (kafka_consumer_group_ConsumerLagMetrics_Value{name=\"OffsetLag\",environmentcode=~\"$EnvironmentCode.+\", topic=~\"$topic\"})",
     "legendFormat": "{{ topic }}:{{ partition }}"
    }
   ]
  },
  { "title": "Load per topic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Bytes In Per 5m",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (topic) (increase(kafka_server_BrokerTopicMetrics_Count{name=\"BytesInPerSec\",environmentcode=~\"$EnvironmentCode.+\", topic=~\"$topic\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per 5m",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (topic) (increase(kafka_server_BrokerTopicMetrics_Count{name=\"BytesOutPerSec\",environmentcode=~\"$EnvironmentCode.+\", topic=~\"$topic\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}