apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: hackweek
  labels:
    app: grafana
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: grafana
  sessionAffinity: None