apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hackweek
  name: prometheus-deployment
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          imagePullPolicy: IfNotPresent
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus/
            - name: storage-volume
              mountPath: /prometheus/
          env:
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  key: apikey
                  name: kafka-secrets
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  key: apisecret
                  name: kafka-secrets
      volumes:
        - name: config-volume
          configMap:
            defaultMode: 420
            name: prometheus-config
        - name: storage-volume
          emptyDir: {}