apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    name: prometheus-config
  namespace: hackweek
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    scrape_configs:
      - job_name: 'kafka-metrics'
        scrape_interval: 1m
        scrape_timeout: 1m
        static_configs:
          - targets:
              - api.telemetry.confluent.cloud
        scheme: https
        basic_auth:
          env:
            - name: username
              valueFrom:
                secretKeyRef:
                  key: apikey
                  name: kafka-secrets
            - name: password
              valueFrom:
                secretKeyRef:
                  key: apisecret
                  name: kafka-secrets
        metrics_path: /v2/metrics/cloud/export
        params:
          "resource.kafka.id":
            - asd
        kubernetes_sd_configs:
          - api_server: null
            role: endpoints
