apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    name: prometheus-config
  namespace: hackweek
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    scrape_configs:
      - job_name: 'prometheus'
        scrape_interval: 1m
        scrape_timeout: 1m
        scheme: http
        static_configs:
        - targets: ['localhost:9090']
        kubernetes_sd_configs:
          - api_server: null
            role: endpoints
