apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    name: prometheus-config
  namespace: hackweek
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    scrape_configs:
      - job_name: 'kafka-metrics'
        scrape_interval: 1m
        scrape_timeout: 1m
        scheme: https
        static_configs:
        - targets: ['api.telemetry.confluent.cloud']
        basic_auth:
          username:
          password:
        metrics_path: /v2/metrics/cloud/export
        params:
          "resource.kafka.id":
            -
        kubernetes_sd_configs:
          - api_server: null
            role: endpoints
